#%RAML 1.0
title: CRM API FOR SALES ORDER HEADER CREATION AND UPDATION
version: 1.0
#baseUri: http://server/api/{version}
schemas: 
  - salesOrderHeader : !include schemas/SalesOrderHeaderRequest.json
resourceTypes: 
  - commonResponse:        
      post:
        responses:
          200: 
            body:
              application/json:
                example: |
                  {
                   "status":"Request is being processed"
                  }
                   
/SalesOrderHeader:
  /Create:
      type: commonResponse
      post:
        description: Create Sales Order Header in CRM
        body:
          application/json:
            schema: salesOrderHeader
            example: !include sampledata/Create_Update_SalesOrderHeader_SampleRequest.json
            
  /Update:
      type: commonResponse
      put:
        description: Update Sales Order Header in CRM 
        body:
          application/json:
            schema: salesOrderHeader
            example: !include sampledata/Create_Update_SalesOrderHeader_SampleRequest.json
